[package]
name = "guardian"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
aes = "0.8.3"
sha2 = { version = "0.10.7", default-features = false }
hmac = { version = "0.12.1", default-features = false }
linked_list_allocator = "0.10.5"
synctools = "0.3.3"
